### ISSUE TITLE
Compiling DBD::MariaDB with strawberry-perl-5.42.0.1-64bit

### ISSUE THREAD

**Issue by zb226** [StrawberryPerl/Perl-Dist-Strawberry#280]
**Warning: While the recipe below did work for my local use case, it's not recommended!
Please read the comments below for more information.**

----

I've spent some time today trying to get the current [`DBD::MariaDB`](https://github.com/perl5-dbi/DBD-MariaDB) (1.24) to work with Strawberry perl 5.42.0.1. The way it should work as per documentation - and the way it does compile on 5.38.2.2 - got me this error when running `gmake`:

    C:/dev/strawberry-perl-5.42.0.1/c/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
    dbdimp.o:dbdimp.c:(.text+0x885): undefined reference to `__imp___pioinfo'

Looking for differences to 5.38.2.2 I found out that 5.42.0.1 does not ship with `c\x86_64-w64-mingw32\lib\libmsvcrt.a`. When I copied this file over to 5.42.0.1, compilation started to work. After that it was necessary to copy `libmariadb.dll` to `c\bin` and then I could use `DBD::MariaDB`.

Is there a problem with 5.42.0.1? Hope this information helps someone.

**Comment by shawnlaffan** [comment]
We use the [winlibs](https://winlibs.com/) distribution for the C compiler and related libs, so everything under the `...c/lib/gcc/` dir is from winlibs.  

In the case of 5.40 and above, we shifted to use the UCRT runtime instead of the MSVCRT runtime.  This [fixed several issues](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues?q=state%3Aclosed%20label%3AUCRT) related to locales but also introduced a few issues with CPAN modules that required patching (e.g. #185).  

It looks like MariaDB falls into the latter category and probably needs some updates to work with UCRT.

**Comment by sisyphus** [comment]
@zb226, just a word of caution regarding your solution:
Presumably the need for the inclusion of libmsvcrt.a signifies that the MSVC runtime is involved.
If, say, a filehandle is created by perl (ie by the UC runtime) and that filehandle gets passed to the MSVC runtime, then the program will probably crash.
And, of course, vice versa - if a handle generated by  MSVCRT gets handed to UCRT it's crash time again.
I don't know if such an issue is likely in your case - with any luck it won't be.
Just something to consider.

Incidentally, if I'm reading https://learn.microsoft.com/en-us/cpp/c-runtime-library/internal-crt-globals-and-functions?view=msvc-170 correctly, <code>__pioinfo</code> should not be called directly.
However, in the DBD-MariaDB-1.24 source, it does get called directly at line 123 of dbdimp.h.

**Comment by zb226** [comment]
Thanks for sharing background information. Yeah, I assumed my dodgy recipe is nothing you'd use in production, I will add a warning above. It worked fine for a little homebrewn webapp, though (i.e. some basic CRUD, nothing fancy).

**Comment by shawnlaffan** [comment]
@zb226 - it's worth raising this as an issue on the [DBD::MariaDB issue tracker](https://github.com/perl5-dbi/DBD-MariaDB/issues).

**Comment by zb226** [comment]
Opened an issue over there. 

I think it might be beneficial to note the MSVCRT/UCRT situation and its implications on the Strawberry homepage? As it is now, people (like me) will download 5.40+ and expect a similar experience to the versions before, i.e. "my DB stuff just works out of the box".

**Comment by shawnlaffan** [comment]
Thanks @zb226 

For purposes of linking, it is https://github.com/perl5-dbi/DBD-MariaDB/issues/231

The website could do with a note regarding the shift to UCRT.  Most modules build without issue but there are always some that depend on specific behaviour.
